name: Deploy Next.js app to AWS Lambda

on:
  push:
    branches:
      - never

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn

      - name: Next build
        run: |
          yarn run build

      - name: Zip files
        run: |
          zip -r app.zip .next

      - name: Upload zip file to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          AWS_S3_BUCKET: untax-app

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
          --function-name untax \
          --s3-bucket untax-app \
          --s3-key untax/app.zip \
          --region eu-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
